### ISSUE TITLE
A script to auto-download/compress the newest hosts file

### ISSUE THREAD

**Issue by Chaython** [Lateralus138/hosts-compress-windows#2] opened 2024-02-26 07:06 UTC
https://github.com/Chaython/useful-registry-keys/blob/main/update_hosts.ps1
This script downloads host-compress
Downloads Steven black's host file
Compresses it using host-compress
Replaces the system32 hosts file
deletes the old hosts file

**Comment by Lateralus138** [comment] 2024-02-26 08:23
This is useful and all and I appreciate it, but I've already written [blackhosts](https://github.com/Lateralus138/blackhosts) to download and install the hosts file and I use **blackhosts**, **hostscompress**, and **IOBit Unlocker** in a *PS1* script I've already written myself to do the same thing you have done, but even then it doesn't always work 100% of the time and the replacement of the system32 hosts file has to be done manually.

The problem is that ***MOST*** people (not sure why you don't have issues; maybe you have DNS caching disabled? I don't recommend that as things like WSL will break) will have a problem overwriting the main hosts file in *system32* because it is ALMOST ALWAYS in use by ***SVCHOSTS*** and even if you have complete ownership of the file you can't do anything with it (delete, replace, etc.) unless you unlock and delete it first (hence IOBit Unlocker or similar).

For said reasons I haven't put my own script here, but I have put instructions on how to do so on the old script version of this (as stated in the main README here) which can be found here: [Hosts Compression Scripts](https://github.com/Lateralus138/hosts-compression-scripts).

Your script does not solve the *file locked* issue that most people will have so I don't think I would post yours and I was already thinking about posting mine here in a new section of the README, but I don't know yet.

I do appreciate your efforts here and I'm glad this works for you, but as stated above this will not work for the average *Windows* user.

Maybe in the near future I will add both your and my script to a "Automation" section, but for now I'm going to close this issue. Please feel free to reply if you like and again, thanks for your effort here.

**Closed as completed by Lateralus138** 2024-02-26 08:23 UTC
